name: jsonpatch

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - _jsonpatch.tpl
      - 'jsonpatch/**'
      - .github/workflows/jsonpatch.yml

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true
          cache: true
          cache-dependency-path: 'jsonpatch/go.sum'

      - name: Go Mod Download
        run: go mod download
        working-directory: jsonpatch

      - name: Test
        run: go test .
        working-directory: jsonpatch
